stages:
- inputs:
  - branch: master
    dir_name: null
    type: git
    service: sample-repo
  jobs:
  - artifact_dir: ""
    name: Build
    type: builder
  name: BUILD
  properties:
  - name: secureTest
    type: secure
  triggers:
  - type: commit
- inputs:
  - dir_name: null
    job: Build
    stage: BUILD
    type: job
  jobs:
  - name: Test
    type: tester
    extension_id: ibm.devops.services.pipeline.bluemix.simplified.shell
    target:
      region_id: ibm:ys1:us-south
      organization: xinyij@ca.ibm.com
      space: dev
    COMMAND: |-
      #!/bin/bash
      # invoke tests here
  - name: Simple Test
    script: |-
      #!/bin/bash
      #Invoke tests here
    test_type: simple
    type: tester
  - name: Test
    type: tester
    script: ''
    test_type: customimage
    docker_image: todo
  name: TEST_EXTENSION
  properties:
  - name: CF_APP_NAME
    type: text
    value: undefined
  - name: APP_URL
    type: text
    value: undefined
  triggers:
  - type: stage
properties: null
